kind: LuaScript
apiVersion: api.ibm.com/v1
metadata:
  name: LuaScript-249ure
  namespace: OpenBanking
  version: '1.0'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  source: |
    console.error("AFTER INVOKE")

    local req = context:get_message('request')

    console.error("Response %s", req)
